var Erizo=Erizo||{};
Erizo.EventDispatcher=function(b){var a={};b.dispatcher={};b.dispatcher.eventListeners={};a.addEventListener=function(a,e){void 0===b.dispatcher.eventListeners[a]&&(b.dispatcher.eventListeners[a]=[]);b.dispatcher.eventListeners[a].push(e)};a.removeEventListener=function(a,e){var g;g=b.dispatcher.eventListeners[a].indexOf(e);-1!==g&&b.dispatcher.eventListeners[a].splice(g,1)};a.dispatchEvent=function(a){var e;L.Logger.debug("Event: "+a.type);for(e in b.dispatcher.eventListeners[a.type])if(b.dispatcher.eventListeners[a.type].hasOwnProperty(e))b.dispatcher.eventListeners[a.type][e](a)};return a};
Erizo.LicodeEvent=function(b){var a={};a.type=b.type;return a};Erizo.RoomEvent=function(b){var a=Erizo.LicodeEvent(b);a.streams=b.streams;return a};Erizo.StreamEvent=function(b){var a=Erizo.LicodeEvent(b);a.stream=b.stream;a.msg=b.msg;return a};Erizo.PublisherEvent=function(b){return Erizo.LicodeEvent(b)};Erizo=Erizo||{};Erizo.FcStack=function(){return{addStream:function(){}}};Erizo=Erizo||{};
Erizo.BowserStack=function(b){var a={},d=webkitRTCPeerConnection;a.pc_config={iceServers:[]};a.con={optional:[{DtlsSrtpKeyAgreement:!0}]};void 0!==b.stunServerUrl&&a.pc_config.iceServers.push({url:b.stunServerUrl});(b.turnServer||{}).url&&a.pc_config.iceServers.push({username:b.turnServer.username,credential:b.turnServer.password,url:b.turnServer.url});void 0===b.audio&&(b.audio=!0);void 0===b.video&&(b.video=!0);a.mediaConstraints={offerToReceiveVideo:b.video,offerToReceiveAudio:b.audio};a.peerConnection=
new d(a.pc_config,a.con);b.remoteDescriptionSet=!1;var e=function(a){if(b.maxVideoBW){var f=a.match(/m=video.*\r\n/);f==null&&(f=a.match(/m=video.*\n/));var j=f[0]+"b=AS:"+b.maxVideoBW+"\r\n",a=a.replace(f[0],j)}if(b.maxAudioBW){f=a.match(/m=audio.*\r\n/);f==null&&(f=a.match(/m=audio.*\n/));j=f[0]+"b=AS:"+b.maxAudioBW+"\r\n";a=a.replace(f[0],j)}return a};a.close=function(){a.state="closed";a.peerConnection.close()};b.localCandidates=[];a.peerConnection.onicecandidate=function(c){if(c.candidate){if(!c.candidate.candidate.match(/a=/))c.candidate.candidate=
"a="+c.candidate.candidate;b.remoteDescriptionSet?b.callback({type:"candidate",candidate:c.candidate}):b.localCandidates.push(c.candidate)}else console.log("End of candidates.",a.peerConnection.localDescription)};a.peerConnection.onaddstream=function(c){if(a.onaddstream)a.onaddstream(c)};a.peerConnection.onremovestream=function(c){if(a.onremovestream)a.onremovestream(c)};var g=function(a){console.log("Error in Stack ",a)},h,i=function(c){c.sdp=e(c.sdp);console.log("Set local description",c.sdp);h=
c;a.peerConnection.setLocalDescription(h,function(){console.log("The final LocalDesc",a.peerConnection.localDescription);b.callback(a.peerConnection.localDescription)},g)},k=function(c){c.sdp=e(c.sdp);b.callback(c);h=c;a.peerConnection.setLocalDescription(c)};a.createOffer=function(c){c===true?a.peerConnection.createOffer(i,g,a.mediaConstraints):a.peerConnection.createOffer(i,g)};a.addStream=function(c){a.peerConnection.addStream(c)};b.remoteCandidates=[];a.processSignalingMessage=function(c){console.log("Process Signaling Message",
c);if(c.type==="offer"){c.sdp=e(c.sdp);a.peerConnection.setRemoteDescription(new RTCSessionDescription(c));a.peerConnection.createAnswer(k,null,a.mediaConstraints);b.remoteDescriptionSet=true}else if(c.type==="answer"){console.log("Set remote description",c.sdp);c.sdp=e(c.sdp);a.peerConnection.setRemoteDescription(new RTCSessionDescription(c),function(){b.remoteDescriptionSet=true;for(console.log("Candidates to be added: ",b.remoteCandidates.length);b.remoteCandidates.length>0;){console.log("Candidate :",
b.remoteCandidates[b.remoteCandidates.length-1]);a.peerConnection.addIceCandidate(b.remoteCandidates.shift(),function(){},g)}for(;b.localCandidates.length>0;)b.callback({type:"candidate",candidate:b.localCandidates.shift()})},function(){console.log("Error Setting Remote Description")})}else if(c.type==="candidate"){console.log("Message with candidate");try{var f;f=typeof c.candidate==="object"?c.candidate:JSON.parse(c.candidate);f.candidate=f.candidate.replace(/a=/g,"");f.sdpMLineIndex=parseInt(f.sdpMLineIndex);
f.sdpMLineIndex=f.sdpMid=="audio"?0:1;var j=new RTCIceCandidate(f);console.log("Remote Candidate",j);b.remoteDescriptionSet?a.peerConnection.addIceCandidate(j,function(){},g):b.remoteCandidates.push(j)}catch(d){L.Logger.error("Error parsing candidate",c.candidate)}}};return a};Erizo=Erizo||{};
Erizo.FirefoxStack=function(b){var a={},d=mozRTCPeerConnection,e=mozRTCSessionDescription,g=mozRTCIceCandidate;a.pc_config={iceServers:[]};void 0!==b.stunServerUrl&&a.pc_config.iceServers.push({url:b.stunServerUrl});(b.turnServer||{}).url&&a.pc_config.iceServers.push({username:b.turnServer.username,credential:b.turnServer.password,url:b.turnServer.url});void 0===b.audio&&(b.audio=!0);void 0===b.video&&(b.video=!0);a.mediaConstraints={offerToReceiveAudio:b.audio,offerToReceiveVideo:b.video,mozDontOfferDataChannel:!0};
a.roapSessionId=103;a.peerConnection=new d(a.pc_config,a.con);b.localCandidates=[];a.peerConnection.onicecandidate=function(a){if(a.candidate){if(!a.candidate.candidate.match(/a=/))a.candidate.candidate="a="+a.candidate.candidate;if(b.remoteDescriptionSet)b.callback({type:"candidate",candidate:a.candidate});else{b.localCandidates.push(a.candidate);console.log("Local Candidates stored: ",b.localCandidates.length,b.localCandidates)}}else console.log("End of candidates.")};a.peerConnection.onaddstream=
function(c){if(a.onaddstream)a.onaddstream(c)};a.peerConnection.onremovestream=function(c){if(a.onremovestream)a.onremovestream(c)};var h=function(a){if(b.video&&b.maxVideoBW){var c=a.match(/m=video.*\r\n/);c==null&&(c=a.match(/m=video.*\n/));var g=c[0]+"b=AS:"+b.maxVideoBW+"\r\n",a=a.replace(c[0],g)}if(b.audio&&b.maxAudioBW){c=a.match(/m=audio.*\r\n/);c==null&&(c=a.match(/m=audio.*\n/));g=c[0]+"b=AS:"+b.maxAudioBW+"\r\n";a=a.replace(c[0],g)}return a},i,k=function(a){a.sdp=h(a.sdp);a.sdp=a.sdp.replace(/a=ice-options:google-ice\r\n/g,
"");b.callback(a);i=a},c=function(c){c.sdp=h(c.sdp);c.sdp=c.sdp.replace(/a=ice-options:google-ice\r\n/g,"");b.callback(c);i=c;a.peerConnection.setLocalDescription(i)};a.createOffer=function(){a.peerConnection.createOffer(k,function(a){L.Logger.error("Error",a)},a.mediaConstraints)};a.addStream=function(c){a.peerConnection.addStream(c)};b.remoteCandidates=[];b.remoteDescriptionSet=!1;a.close=function(){a.state="closed";a.peerConnection.close()};a.processSignalingMessage=function(f){if(f.type==="offer"){f.sdp=
h(f.sdp);a.peerConnection.setRemoteDescription(new e(f));a.peerConnection.createAnswer(c,function(a){L.Logger.error("Error",a)},a.mediaConstraints);b.remoteDescriptionSet=true}else if(f.type==="answer"){console.log("Set remote and local description",f.sdp);f.sdp=h(f.sdp);a.peerConnection.setLocalDescription(i,function(){a.peerConnection.setRemoteDescription(new e(f),function(){for(b.remoteDescriptionSet=true;b.remoteCandidates.length>0;)a.peerConnection.addIceCandidate(b.remoteCandidates.shift());
for(;b.localCandidates.length>0;){L.Logger.info("Sending Candidate");b.callback({type:"candidate",candidate:b.localCandidates.shift()})}})})}else if(f.type==="candidate")try{var j;j=typeof f.candidate==="object"?f.candidate:JSON.parse(f.candidate);j.candidate=j.candidate.replace(/ generation 0/g,"");j.candidate=j.candidate.replace(/ udp /g," UDP ");j.sdpMLineIndex=parseInt(j.sdpMLineIndex);var d=new g(j);b.remoteDescriptionSet?a.peerConnection.addIceCandidate(d):b.remoteCandidates.push(d)}catch(p){L.Logger.error("Error parsing candidate",
f.candidate,p)}};return a};Erizo=Erizo||{};
Erizo.ChromeStableStack=function(b){var a={},d=webkitRTCPeerConnection;a.pc_config={iceServers:[]};a.con={optional:[{DtlsSrtpKeyAgreement:!0}]};void 0!==b.stunServerUrl&&a.pc_config.iceServers.push({url:b.stunServerUrl});(b.turnServer||{}).url&&a.pc_config.iceServers.push({username:b.turnServer.username,credential:b.turnServer.password,url:b.turnServer.url});void 0===b.audio&&(b.audio=!0);void 0===b.video&&(b.video=!0);a.mediaConstraints={mandatory:{OfferToReceiveVideo:b.video,OfferToReceiveAudio:b.audio}};var e=
function(a){console.log("Error in Stack ",a)};a.peerConnection=new d(a.pc_config,a.con);var g=function(a){if(b.video&&b.maxVideoBW){var f=a.match(/m=video.*\r\n/);f==null&&(f=a.match(/m=video.*\n/));var j=f[0]+"b=AS:"+b.maxVideoBW+"\r\n",a=a.replace(f[0],j)}if(b.audio&&b.maxAudioBW){f=a.match(/m=audio.*\r\n/);f==null&&(f=a.match(/m=audio.*\n/));j=f[0]+"b=AS:"+b.maxAudioBW+"\r\n";a=a.replace(f[0],j)}return a};a.close=function(){a.state="closed";a.peerConnection.close()};b.localCandidates=[];a.peerConnection.onicecandidate=
function(a){if(a.candidate){if(!a.candidate.candidate.match(/a=/))a.candidate.candidate="a="+a.candidate.candidate;if(b.remoteDescriptionSet)b.callback({type:"candidate",candidate:a.candidate});else{b.localCandidates.push(a.candidate);console.log("Local Candidates stored: ",b.localCandidates.length,b.localCandidates)}}else console.log("End of candidates.")};a.peerConnection.onaddstream=function(c){if(a.onaddstream)a.onaddstream(c)};a.peerConnection.onremovestream=function(c){if(a.onremovestream)a.onremovestream(c)};
var h,i=function(a){a.sdp=g(a.sdp);a.sdp=a.sdp.replace(/a=ice-options:google-ice\r\n/g,"");b.callback(a);h=a},k=function(c){c.sdp=g(c.sdp);c.sdp=c.sdp.replace(/a=ice-options:google-ice\r\n/g,"");b.callback(c);h=c;a.peerConnection.setLocalDescription(c)};a.createOffer=function(c){c===true?a.peerConnection.createOffer(i,e,a.mediaConstraints):a.peerConnection.createOffer(i,e)};a.addStream=function(c){a.peerConnection.addStream(c)};b.remoteCandidates=[];b.remoteDescriptionSet=!1;a.processSignalingMessage=
function(c){if(c.type==="offer"){c.sdp=g(c.sdp);a.peerConnection.setRemoteDescription(new RTCSessionDescription(c));a.peerConnection.createAnswer(k,null,a.mediaConstraints);b.remoteDescriptionSet=true}else if(c.type==="answer"){console.log("Set remote and local description",c.sdp);c.sdp=g(c.sdp);a.peerConnection.setLocalDescription(h,function(){a.peerConnection.setRemoteDescription(new RTCSessionDescription(c),function(){b.remoteDescriptionSet=true;for(console.log("Candidates to be added: ",b.remoteCandidates.length,
b.remoteCandidates);b.remoteCandidates.length>0;)a.peerConnection.addIceCandidate(b.remoteCandidates.shift());for(console.log("Local candidates to send:",b.localCandidates.length);b.localCandidates.length>0;)b.callback({type:"candidate",candidate:b.localCandidates.shift()})})})}else if(c.type==="candidate")try{var f;f=typeof c.candidate==="object"?c.candidate:JSON.parse(c.candidate);f.candidate=f.candidate.replace(/a=/g,"");f.sdpMLineIndex=parseInt(f.sdpMLineIndex);var j=new RTCIceCandidate(f);b.remoteDescriptionSet?
a.peerConnection.addIceCandidate(j):b.remoteCandidates.push(j)}catch(e){L.Logger.error("Error parsing candidate",c.candidate)}};return a};Erizo=Erizo||{};
Erizo.ChromeCanaryStack=function(b){var a={},d=webkitRTCPeerConnection;a.pc_config={iceServers:[]};a.con={optional:[{DtlsSrtpKeyAgreement:!0}]};void 0!==b.stunServerUrl&&a.pc_config.iceServers.push({url:b.stunServerUrl});(b.turnServer||{}).url&&a.pc_config.iceServers.push({username:b.turnServer.username,credential:b.turnServer.password,url:b.turnServer.url});if(void 0===b.audio||b.nop2p)b.audio=!0;if(void 0===b.video||b.nop2p)b.video=!0;a.mediaConstraints={mandatory:{OfferToReceiveVideo:b.video,OfferToReceiveAudio:b.audio}};
a.roapSessionId=103;a.peerConnection=new d(a.pc_config,a.con);a.peerConnection.onicecandidate=function(g){L.Logger.debug("PeerConnection: ",b.session_id);if(g.candidate)a.iceCandidateCount+=1;else if(L.Logger.debug("State: "+a.peerConnection.iceGatheringState),void 0===a.ices&&(a.ices=0),a.ices+=1,1<=a.ices&&a.moreIceComing)a.moreIceComing=!1,a.markActionNeeded()};var e=function(a){if(b.maxVideoBW)var e=a.match(/m=video.*\r\n/),d=e[0]+"b=AS:"+b.maxVideoBW+"\r\n",a=a.replace(e[0],d);b.maxAudioBW&&
(e=a.match(/m=audio.*\r\n/),d=e[0]+"b=AS:"+b.maxAudioBW+"\r\n",a=a.replace(e[0],d));return a};a.processSignalingMessage=function(b){L.Logger.debug("Activity on conn "+a.sessionId);b=JSON.parse(b);a.incomingMessage=b;"new"===a.state?"OFFER"===b.messageType?(b={sdp:b.sdp,type:"offer"},a.peerConnection.setRemoteDescription(new RTCSessionDescription(b)),a.state="offer-received",a.markActionNeeded()):a.error("Illegal message for this state: "+b.messageType+" in state "+a.state):"offer-sent"===a.state?
"ANSWER"===b.messageType?(b={sdp:b.sdp,type:"answer"},L.Logger.debug("Received ANSWER: ",b.sdp),b.sdp=e(b.sdp),a.peerConnection.setRemoteDescription(new RTCSessionDescription(b)),a.sendOK(),a.state="established"):"pr-answer"===b.messageType?(b={sdp:b.sdp,type:"pr-answer"},a.peerConnection.setRemoteDescription(new RTCSessionDescription(b))):"offer"===b.messageType?a.error("Not written yet"):a.error("Illegal message for this state: "+b.messageType+" in state "+a.state):"established"===a.state&&("OFFER"===
b.messageType?(b={sdp:b.sdp,type:"offer"},a.peerConnection.setRemoteDescription(new RTCSessionDescription(b)),a.state="offer-received",a.markActionNeeded()):a.error("Illegal message for this state: "+b.messageType+" in state "+a.state))};a.addStream=function(b){a.peerConnection.addStream(b);a.markActionNeeded()};a.removeStream=function(){a.markActionNeeded()};a.close=function(){a.state="closed";a.peerConnection.close()};a.markActionNeeded=function(){a.actionNeeded=!0;a.doLater(function(){a.onstablestate()})};
a.doLater=function(a){window.setTimeout(a,1)};a.onstablestate=function(){var b;if(a.actionNeeded){if("new"===a.state||"established"===a.state)a.peerConnection.createOffer(function(b){b.sdp=e(b.sdp);L.Logger.debug("Changed",b.sdp);b.sdp!==a.prevOffer?(a.peerConnection.setLocalDescription(b),a.state="preparing-offer",a.markActionNeeded()):L.Logger.debug("Not sending a new offer")},null,a.mediaConstraints);else if("preparing-offer"===a.state){if(a.moreIceComing)return;a.prevOffer=a.peerConnection.localDescription.sdp;
L.Logger.debug("Sending OFFER: "+a.prevOffer);a.sendMessage("OFFER",a.prevOffer);a.state="offer-sent"}else if("offer-received"===a.state)a.peerConnection.createAnswer(function(b){a.peerConnection.setLocalDescription(b);a.state="offer-received-preparing-answer";a.iceStarted?a.markActionNeeded():(L.Logger.debug((new Date).getTime()+": Starting ICE in responder"),a.iceStarted=!0)},null,a.mediaConstraints);else if("offer-received-preparing-answer"===a.state){if(a.moreIceComing)return;b=a.peerConnection.localDescription.sdp;
a.sendMessage("ANSWER",b);a.state="established"}else a.error("Dazed and confused in state "+a.state+", stopping here");a.actionNeeded=!1}};a.sendOK=function(){a.sendMessage("OK")};a.sendMessage=function(b,e){var d={};d.messageType=b;d.sdp=e;"OFFER"===b?(d.offererSessionId=a.sessionId,d.answererSessionId=a.otherSessionId,d.seq=a.sequenceNumber+=1,d.tiebreaker=Math.floor(429496723*Math.random()+1)):(d.offererSessionId=a.incomingMessage.offererSessionId,d.answererSessionId=a.sessionId,d.seq=a.incomingMessage.seq);
a.onsignalingmessage(JSON.stringify(d))};a.error=function(a){throw"Error in RoapOnJsep: "+a;};a.sessionId=a.roapSessionId+=1;a.sequenceNumber=0;a.actionNeeded=!1;a.iceStarted=!1;a.moreIceComing=!0;a.iceCandidateCount=0;a.onsignalingmessage=b.callback;a.peerConnection.onopen=function(){if(a.onopen)a.onopen()};a.peerConnection.onaddstream=function(b){if(a.onaddstream)a.onaddstream(b)};a.peerConnection.onremovestream=function(b){if(a.onremovestream)a.onremovestream(b)};a.peerConnection.oniceconnectionstatechange=
function(b){if(a.oniceconnectionstatechange)a.oniceconnectionstatechange(b.currentTarget.iceConnectionState)};a.onaddstream=null;a.onremovestream=null;a.state="new";a.markActionNeeded();return a};Erizo=Erizo||{};Erizo.sessionId=103;
Erizo.Connection=function(b){var a={};b.session_id=Erizo.sessionId+=1;a.browser=Erizo.getBrowser();if("undefined"!==typeof module&&module.exports)L.Logger.error("Publish/subscribe video/audio streams not supported in erizofc yet"),a=Erizo.FcStack(b);else if("mozilla"===a.browser)L.Logger.debug("Firefox Stack"),a=Erizo.FirefoxStack(b);else if("bowser"===a.browser)L.Logger.debug("Bowser Stack"),a=Erizo.BowserStack(b);else if("chrome-stable"===a.browser)L.Logger.debug("Stable!"),a=Erizo.ChromeStableStack(b);
else throw L.Logger.debug("None!"),"WebRTC stack not available";return a};
Erizo.getBrowser=function(){var b="none";null!==window.navigator.userAgent.match("Firefox")?b="mozilla":null!==window.navigator.userAgent.match("Bowser")?b="bowser":null!==window.navigator.userAgent.match("Chrome")?26<=window.navigator.appVersion.match(/Chrome\/([\w\W]*?)\./)[1]&&(b="chrome-stable"):null!==window.navigator.userAgent.match("Safari")?b="bowser":null!==window.navigator.userAgent.match("AppleWebKit")&&(b="bowser");return b};
Erizo.GetUserMedia=function(b,a,d){navigator.getMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia;if(b.screen)if(L.Logger.debug("Screen access requested"),34<=!window.navigator.appVersion.match(/Chrome\/([\w\W]*?)\./)[1])d({code:"This browser does not support screen sharing"});else{var e="okeephmleflklcdebijnponpabbmmgeo";b.extensionId&&(L.Logger.debug("extensionId supplied, using "+b.extensionId),e=b.extensionId);L.Logger.debug("Screen access on chrome stable, looking for extension");
try{chrome.runtime.sendMessage(e,{getStream:!0},function(e){if(e==void 0){L.Logger.debug("Access to screen denied");d({code:"Access to screen denied"})}else{b={video:{mandatory:{chromeMediaSource:"desktop",chromeMediaSourceId:e.streamId}}};navigator.getMedia(b,a,d)}})}catch(g){L.Logger.debug("Lynckia screensharing plugin is not accessible "),d({code:"no_plugin_present"})}}else"undefined"!==typeof module&&module.exports?L.Logger.error("Video/audio streams not supported in erizofc yet"):navigator.getMedia(b,
a,d)};Erizo=Erizo||{};
Erizo.Stream=function(b){var a=Erizo.EventDispatcher(b),d;a.stream=b.stream;a.url=b.url;a.recording=b.recording;a.room=void 0;a.showing=!1;a.local=!1;a.video=b.video;a.audio=b.audio;a.screen=b.screen;a.videoSize=b.videoSize;a.extensionId=b.extensionId;if(void 0!==a.videoSize&&(!(a.videoSize instanceof Array)||4!=a.videoSize.length))throw Error("Invalid Video Size");if(void 0===b.local||!0===b.local)a.local=!0;a.getID=function(){return b.streamID};a.getAttributes=function(){return b.attributes};a.setAttributes=
function(){L.Logger.error("Failed to set attributes data. This Stream object has not been published.")};a.updateLocalAttributes=function(a){b.attributes=a};a.hasAudio=function(){return b.audio};a.hasVideo=function(){return b.video};a.hasData=function(){return b.data};a.hasScreen=function(){return b.screen};a.sendData=function(){L.Logger.error("Failed to send data. This Stream object has not that channel enabled.")};a.init=function(){try{if((b.audio||b.video||b.screen)&&void 0===b.url){L.Logger.debug("Requested access to local media");
var d=b.video;!0==d&&void 0!==a.videoSize&&(d={mandatory:{minWidth:a.videoSize[0],minHeight:a.videoSize[1],maxWidth:a.videoSize[2],maxHeight:a.videoSize[3]}});var g={video:d,audio:b.audio,fake:b.fake,screen:b.screen,extensionId:a.extensionId};L.Logger.debug(g);Erizo.GetUserMedia(g,function(b){L.Logger.info("User has granted access to local media.");a.stream=b;b=Erizo.StreamEvent({type:"access-accepted"});a.dispatchEvent(b)},function(b){L.Logger.error("Failed to get access to local media. Error code was "+
b.code+".");b=Erizo.StreamEvent({type:"access-denied"});a.dispatchEvent(b)})}else{var h=Erizo.StreamEvent({type:"access-accepted"});a.dispatchEvent(h)}}catch(i){L.Logger.error("Error accessing to local media",i)}};a.close=function(){a.local&&(void 0!==a.room&&a.room.unpublish(a),a.hide(),void 0!==a.stream&&a.stream.stop(),a.stream=void 0)};a.play=function(b,d){d=d||{};a.elementID=b;if(a.hasVideo()||this.hasScreen()){if(void 0!==b){var h=new Erizo.VideoPlayer({id:a.getID(),stream:a,elementID:b,options:d});
a.player=h;a.showing=!0}}else a.hasAudio&&(h=new Erizo.AudioPlayer({id:a.getID(),stream:a,elementID:b,options:d}),a.player=h,a.showing=!0)};a.stop=function(){a.showing&&void 0!==a.player&&(a.player.destroy(),a.showing=!1)};a.show=a.play;a.hide=a.stop;d=function(){if(void 0!==a.player&&void 0!==a.stream){var b=a.player.video,d=document.defaultView.getComputedStyle(b),h=parseInt(d.getPropertyValue("width"),10),i=parseInt(d.getPropertyValue("height"),10),k=parseInt(d.getPropertyValue("left"),10),d=parseInt(d.getPropertyValue("top"),
10),c=document.getElementById(a.elementID),f=document.defaultView.getComputedStyle(c),c=parseInt(f.getPropertyValue("width"),10),f=parseInt(f.getPropertyValue("height"),10),j=document.createElement("canvas");j.id="testing";j.width=c;j.height=f;j.setAttribute("style","display: none");j.getContext("2d").drawImage(b,k,d,h,i);return j}return null};a.getVideoFrameURL=function(a){var b=d();return null!==b?a?b.toDataURL(a):b.toDataURL():null};a.getVideoFrame=function(){var a=d();return null!==a?a.getContext("2d").getImageData(0,
0,a.width,a.height):null};return a};Erizo=Erizo||{};
Erizo.Room=function(b){var a=Erizo.EventDispatcher(b),d,e,g,h,i,k;a.remoteStreams={};a.localStreams={};a.roomID="";a.socket={};a.state=0;a.p2p=!1;a.addEventListener("room-disconnected",function(){var b,f;a.state=0;for(b in a.remoteStreams)a.remoteStreams.hasOwnProperty(b)&&(f=a.remoteStreams[b],k(f),delete a.remoteStreams[b],f=Erizo.StreamEvent({type:"stream-removed",stream:f}),a.dispatchEvent(f));a.remoteStreams={};for(b in a.localStreams)a.localStreams.hasOwnProperty(b)&&(f=a.localStreams[b],f.pc.close(),
delete a.localStreams[b]);try{a.socket.disconnect()}catch(j){L.Logger.debug("Socket already disconnected")}a.socket=void 0});k=function(a){void 0!==a.stream&&(a.hide(),a.pc&&a.pc.close(),a.local&&a.stream.stop())};h=function(a,b){a.local?e("sendDataStream",{id:a.getID(),msg:b}):L.Logger.error("You can not send data through a remote stream")};i=function(a,b){a.local?(a.updateLocalAttributes(b),e("updateStreamAttributes",{id:a.getID(),attrs:b})):L.Logger.error("You can not update attributes in a remote stream")};
d=function(c,f,j){console.log(c);a.socket=io.connect(c.host,{reconnect:!1,secure:c.secure,"force new connection":!0});a.socket.on("onAddStream",function(b){var c=Erizo.Stream({streamID:b.id,local:!1,audio:b.audio,video:b.video,data:b.data,screen:b.screen,attributes:b.attributes});a.remoteStreams[b.id]=c;b=Erizo.StreamEvent({type:"stream-added",stream:c});a.dispatchEvent(b)});a.socket.on("signaling_message_erizo",function(b){var c;(c=b.peerId?a.remoteStreams[b.peerId]:a.localStreams[b.streamId])&&
c.pc.processSignalingMessage(b.mess)});a.socket.on("signaling_message_peer",function(b){var c=a.localStreams[b.streamId];c?c.pc[b.peerSocket].processSignalingMessage(b.msg):(c=a.remoteStreams[b.streamId],c.pc||d(c,b.peerSocket),c.pc.processSignalingMessage(b.msg))});a.socket.on("publish_me",function(b){var c=a.localStreams[b.streamId];void 0===c.pc&&(c.pc={});c.pc[b.peerSocket]=Erizo.Connection({callback:function(a){g("signaling_message",{streamId:b.streamId,peerSocket:b.peerSocket,msg:a})},audio:c.hasAudio(),
video:c.hasVideo(),stunServerUrl:a.stunServerUrl,turnServer:a.turnServer});c.pc[b.peerSocket].oniceconnectionstatechange=function(a){if(a==="disconnected"){c.pc[b.peerSocket].close();delete c.pc[b.peerSocket]}};c.pc[b.peerSocket].addStream(c.stream);c.pc[b.peerSocket].createOffer()});var d=function(c,f){c.pc=Erizo.Connection({callback:function(a){g("signaling_message",{streamId:c.getID(),peerSocket:f,msg:a})},stunServerUrl:a.stunServerUrl,turnServer:a.turnServer,maxAudioBW:b.maxAudioBW,maxVideoBW:b.maxVideoBW});
c.pc.onaddstream=function(b){L.Logger.info("Stream subscribed");c.stream=b.stream;b=Erizo.StreamEvent({type:"stream-subscribed",stream:c});a.dispatchEvent(b)}};a.socket.on("onDataStream",function(b){var c=a.remoteStreams[b.id],b=Erizo.StreamEvent({type:"stream-data",msg:b.msg,stream:c});c.dispatchEvent(b)});a.socket.on("onUpdateAttributeStream",function(b){var c=a.remoteStreams[b.id],f=Erizo.StreamEvent({type:"stream-attributes-update",attrs:b.attrs,stream:c});c.updateLocalAttributes(b.attrs);c.dispatchEvent(f)});
a.socket.on("onRemoveStream",function(b){var c=a.remoteStreams[b.id];delete a.remoteStreams[b.id];k(c);b=Erizo.StreamEvent({type:"stream-removed",stream:c});a.dispatchEvent(b)});a.socket.on("disconnect",function(){L.Logger.info("Socket disconnected");if(0!==a.state){var b=Erizo.RoomEvent({type:"room-disconnected"});a.dispatchEvent(b)}});a.socket.on("connection_failed",function(){L.Logger.info("ICE Connection Failed");if(0!==a.state){var b=Erizo.RoomEvent({type:"stream-failed"});a.dispatchEvent(b)}});
e("token",c,f,j)};e=function(b,f,j,d){a.socket.emit(b,f,function(a,b){"success"===a?void 0!==j&&j(b):"error"===a?void 0!==d&&d(b):void 0!==j&&j(a,b)})};g=function(b,f,j,d){a.socket.emit(b,f,j,function(a,b){void 0!==d&&d(a,b)})};a.connect=function(){var c=L.Base64.decodeBase64(b.token);0!==a.state&&L.Logger.error("Room already connected");a.state=1;d(JSON.parse(c),function(c){var j=0,d=[],e,g,h;e=c.streams||[];a.p2p=c.p2p;g=c.id;a.stunServerUrl=c.stunServerUrl;a.turnServer=c.turnServer;a.state=2;b.defaultVideoBW=
c.defaultVideoBW;b.maxVideoBW=c.maxVideoBW;for(j in e)e.hasOwnProperty(j)&&(h=e[j],c=Erizo.Stream({streamID:h.id,local:!1,audio:h.audio,video:h.video,data:h.data,screen:h.screen,attributes:h.attributes}),d.push(c),a.remoteStreams[h.id]=c);a.roomID=g;L.Logger.info("Connected to room "+a.roomID);j=Erizo.RoomEvent({type:"room-connected",streams:d});a.dispatchEvent(j)},function(a){L.Logger.error("Not Connected! Error: "+a)})};a.disconnect=function(){var b=Erizo.RoomEvent({type:"room-disconnected"});a.dispatchEvent(b)};
a.publish=function(c,f,d){f=f||{};f.maxVideoBW=f.maxVideoBW||b.defaultVideoBW;f.maxVideoBW>b.maxVideoBW&&(f.maxVideoBW=b.maxVideoBW);if(c.local&&void 0===a.localStreams[c.getID()])if(c.hasAudio()||c.hasVideo()||c.hasScreen())if(void 0!==c.url||void 0!==c.recording){var e,p;c.url?(e="url",p=c.url):(e="recording",p=c.recording);g("publish",{state:e,data:c.hasData(),audio:c.hasAudio(),video:c.hasVideo(),attributes:c.getAttributes()},p,function(b,f){if(b!==null){L.Logger.info("Stream published");c.getID=
function(){return b};c.sendData=function(a){h(c,a)};c.setAttributes=function(a){i(c,a)};a.localStreams[b]=c;c.room=a;d&&d(b)}else{L.Logger.error("Error when publishing the stream",f);d&&d(void 0,f)}})}else a.p2p?(b.maxAudioBW=f.maxAudioBW,b.maxVideoBW=f.maxVideoBW,g("publish",{state:"p2p",data:c.hasData(),audio:c.hasAudio(),video:c.hasVideo(),screen:c.hasScreen(),attributes:c.getAttributes()},void 0,function(b,f){if(b===null){L.Logger.error("Error when publishing the stream",f);d&&d(void 0,f)}L.Logger.info("Stream published");
c.getID=function(){return b};if(c.hasData())c.sendData=function(a){h(c,a)};c.setAttributes=function(a){i(c,a)};a.localStreams[b]=c;c.room=a})):g("publish",{state:"erizo",data:c.hasData(),audio:c.hasAudio(),video:c.hasVideo(),screen:c.hasScreen(),attributes:c.getAttributes()},void 0,function(b,e){if(b===null){L.Logger.error("Error when publishing the stream: ",e);d&&d(void 0,e)}else{L.Logger.info("Stream published");c.getID=function(){return b};if(c.hasData())c.sendData=function(a){h(c,a)};a.localStreams[b]=
c;c.room=a;c.pc=Erizo.Connection({callback:function(a){console.log("Sending message",a);g("signaling_message",{streamId:c.getID(),msg:a},void 0,function(){})},stunServerUrl:a.stunServerUrl,turnServer:a.turnServer,maxAudioBW:f.maxAudioBW,maxVideoBW:f.maxVideoBW,audio:c.hasAudio(),video:c.hasVideo()});c.pc.addStream(c.stream);c.pc.createOffer();d&&d(b)}});else c.hasData()&&g("publish",{state:"data",data:c.hasData(),audio:!1,video:!1,screen:!1,attributes:c.getAttributes()},void 0,function(b,f){if(b===
null){L.Logger.error("Error publishing stream ",f);d&&d(void 0,f)}else{L.Logger.info("Stream published");c.getID=function(){return b};c.sendData=function(a){h(c,a)};c.setAttributes=function(a){i(c,a)};a.localStreams[b]=c;c.room=a;d&&d(b)}})};a.startRecording=function(a,b){L.Logger.debug("Start Recording streamaa: "+a.getID());e("startRecorder",{to:a.getID()},function(a,c){null===a?(L.Logger.error("Error on start recording",c),b&&b(void 0,c)):(L.Logger.info("Start recording",a),b&&b(a))})};a.stopRecording=
function(a,b){e("stopRecorder",{id:a},function(a,c){null===a?(L.Logger.error("Error on stop recording",c),b&&b(void 0,c)):(L.Logger.info("Stop recording"),b&&b(!0))})};a.unpublish=function(b,f){if(b.local){e("unpublish",b.getID(),function(a,b){null===a?(L.Logger.error("Error unpublishing stream",b),f&&f(void 0,b)):(L.Logger.info("Stream unpublished"),f&&f(!0))});var d=b.room.p2p;b.room=void 0;if((b.hasAudio()||b.hasVideo()||b.hasScreen())&&void 0===b.url&&!d)b.pc.close(),b.pc=void 0;delete a.localStreams[b.getID()];
b.getID=function(){};b.sendData=function(){};b.setAttributes=function(){}}};a.subscribe=function(b,f,d){f=f||{};if(!b.local){if(b.hasVideo()||b.hasAudio()||b.hasScreen())a.p2p?(g("subscribe",{streamId:b.getID()}),d&&d(!0)):g("subscribe",{streamId:b.getID(),audio:f.audio,video:f.video,data:f.data,browser:Erizo.getBrowser()},void 0,function(f,e){null===f?(L.Logger.error("Error subscribing to stream ",e),d&&d(void 0,e)):(L.Logger.info("Subscriber added"),b.pc=Erizo.Connection({callback:function(a){L.Logger.info("Sending message",
a);g("signaling_message",{streamId:b.getID(),msg:a,browser:b.pc.browser},void 0,function(){})},nop2p:!0,audio:b.hasAudio(),video:b.hasVideo(),stunServerUrl:a.stunServerUrl,turnServer:a.turnServer}),b.pc.onaddstream=function(f){L.Logger.info("Stream subscribed");b.stream=f.stream;f=Erizo.StreamEvent({type:"stream-subscribed",stream:b});a.dispatchEvent(f)},b.pc.createOffer(!0),d&&d(!0))});else if(b.hasData()&&!1!==f.data)g("subscribe",{streamId:b.getID(),data:f.data},void 0,function(f,e){if(null===
f)L.Logger.error("Error subscribing to stream ",e),d&&d(void 0,e);else{L.Logger.info("Stream subscribed");var g=Erizo.StreamEvent({type:"stream-subscribed",stream:b});a.dispatchEvent(g);d&&d(!0)}});else{L.Logger.info("Subscribing to anything");return}L.Logger.info("Subscribing to: "+b.getID())}};a.unsubscribe=function(b,f){void 0!==a.socket&&(b.local||e("unsubscribe",b.getID(),function(a,d){null===a?f&&f(void 0,d):(k(b),f&&f(!0))},function(){L.Logger.error("Error calling unsubscribe.")}))};a.getStreamsByAttribute=
function(b,f){var d=[],e,g;for(e in a.remoteStreams)a.remoteStreams.hasOwnProperty(e)&&(g=a.remoteStreams[e],void 0!==g.getAttributes()&&void 0!==g.getAttributes()[b]&&g.getAttributes()[b]===f&&d.push(g));return d};return a};var L=L||{};
L.Logger=function(b){return{DEBUG:0,TRACE:1,INFO:2,WARNING:3,ERROR:4,NONE:5,enableLogPanel:function(){b.Logger.panel=document.createElement("textarea");b.Logger.panel.setAttribute("id","licode-logs");b.Logger.panel.setAttribute("style","width: 100%; height: 100%; display: none");b.Logger.panel.setAttribute("rows",20);b.Logger.panel.setAttribute("cols",20);b.Logger.panel.setAttribute("readOnly",!0);document.body.appendChild(b.Logger.panel)},setLogLevel:function(a){a>b.Logger.NONE?a=b.Logger.NONE:a<
b.Logger.DEBUG&&(a=b.Logger.DEBUG);b.Logger.logLevel=a},log:function(a){var d="";if(!(a<b.Logger.logLevel)){a===b.Logger.DEBUG?d+="DEBUG":a===b.Logger.TRACE?d+="TRACE":a===b.Logger.INFO?d+="INFO":a===b.Logger.WARNING?d+="WARNING":a===b.Logger.ERROR&&(d+="ERROR");for(var d=d+": ",e=[],g=0;g<arguments.length;g++)e[g]=arguments[g];e=e.slice(1);e=[d].concat(e);if(void 0!==b.Logger.panel){d="";for(g=0;g<e.length;g++)d+=e[g];b.Logger.panel.value=b.Logger.panel.value+"\n"+d}else console.log.apply(console,
e)}},debug:function(){for(var a=[],d=0;d<arguments.length;d++)a[d]=arguments[d];b.Logger.log.apply(b.Logger,[b.Logger.DEBUG].concat(a))},trace:function(){for(var a=[],d=0;d<arguments.length;d++)a[d]=arguments[d];b.Logger.log.apply(b.Logger,[b.Logger.TRACE].concat(a))},info:function(){for(var a=[],d=0;d<arguments.length;d++)a[d]=arguments[d];b.Logger.log.apply(b.Logger,[b.Logger.INFO].concat(a))},warning:function(){for(var a=[],d=0;d<arguments.length;d++)a[d]=arguments[d];b.Logger.log.apply(b.Logger,
[b.Logger.WARNING].concat(a))},error:function(){for(var a=[],d=0;d<arguments.length;d++)a[d]=arguments[d];b.Logger.log.apply(b.Logger,[b.Logger.ERROR].concat(a))}}}(L);L=L||{};
L.Base64=function(){var b,a,d,e,g,h,i,k,c;b="A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9,+,/".split(",");a=[];for(g=0;g<b.length;g+=1)a[b[g]]=g;h=function(a){d=a;e=0};i=function(){var a;if(!d||e>=d.length)return-1;a=d.charCodeAt(e)&255;e+=1;return a};k=function(){if(!d)return-1;for(;;){if(e>=d.length)return-1;var b=d.charAt(e);e+=1;if(a[b])return a[b];if("A"===b)return 0}};c=function(a){a=a.toString(16);1===a.length&&(a=
"0"+a);return unescape("%"+a)};return{encodeBase64:function(a){var c,d,e;h(a);a="";c=Array(3);d=0;for(e=!1;!e&&-1!==(c[0]=i());)if(c[1]=i(),c[2]=i(),a+=b[c[0]>>2],-1!==c[1]?(a+=b[c[0]<<4&48|c[1]>>4],-1!==c[2]?(a+=b[c[1]<<2&60|c[2]>>6],a+=b[c[2]&63]):(a+=b[c[1]<<2&60],a+="=",e=!0)):(a+=b[c[0]<<4&48],a+="=",a+="=",e=!0),d+=4,76<=d)a+="\n",d=0;return a},decodeBase64:function(a){var b,d;h(a);a="";b=Array(4);for(d=!1;!d&&-1!==(b[0]=k())&&-1!==(b[1]=k());)b[2]=k(),b[3]=k(),a+=c(b[0]<<2&255|b[1]>>4),-1!==
b[2]?(a+=c(b[1]<<4&255|b[2]>>2),-1!==b[3]?a+=c(b[2]<<6&255|b[3]):d=!0):d=!0;return a}}}(L);(function(){function b(){(new L.ElementQueries).init()}this.L=this.L||{};this.L.ElementQueries=function(){function a(a){a||(a=document.documentElement);a=getComputedStyle(a,"fontSize");return parseFloat(a)||16}function b(c,d){var e=d.replace(/[0-9]*/,""),d=parseFloat(d);switch(e){case "px":return d;case "em":return d*a(c);case "rem":return d*a();case "vw":return d*document.documentElement.clientWidth/100;case "vh":return d*document.documentElement.clientHeight/100;case "vmin":case "vmax":return d*
(0,Math["vmin"===e?"min":"max"])(document.documentElement.clientWidth/100,document.documentElement.clientHeight/100);default:return d}}function e(a){this.element=a;this.options=[];var f,e,g,h=0,i=0,k,n,l,m,o;this.addOption=function(a){this.options.push(a)};var q=["min-width","min-height","max-width","max-height"];this.call=function(){h=this.element.offsetWidth;i=this.element.offsetHeight;l={};f=0;for(e=this.options.length;f<e;f++)g=this.options[f],k=b(this.element,g.value),n="width"==g.property?h:
i,o=g.mode+"-"+g.property,m="","min"==g.mode&&n>=k&&(m+=g.value),"max"==g.mode&&n<=k&&(m+=g.value),l[o]||(l[o]=""),m&&-1===(" "+l[o]+" ").indexOf(" "+m+" ")&&(l[o]+=" "+m);for(var a in q)l[q[a]]?this.element.setAttribute(q[a],l[q[a]].substr(1)):this.element.removeAttribute(q[a])}}function g(a,b){a.elementQueriesSetupInformation?a.elementQueriesSetupInformation.addOption(b):(a.elementQueriesSetupInformation=new e(a),a.elementQueriesSetupInformation.addOption(b),new ResizeSensor(a,function(){a.elementQueriesSetupInformation.call()}));
a.elementQueriesSetupInformation.call()}function h(a){for(var b,a=a.replace(/'/g,'"');null!==(b=k.exec(a));)if(5<b.length){var d=b[1]||b[5],e=b[2],h=b[3];b=b[4];var i=void 0;document.querySelectorAll&&(i=document.querySelectorAll.bind(document));!i&&"undefined"!==typeof $$&&(i=$$);!i&&"undefined"!==typeof jQuery&&(i=jQuery);if(!i)throw"No document.querySelectorAll, jQuery or Mootools's $$ found.";for(var d=i(d),i=0,r=d.length;i<r;i++)g(d[i],{mode:e,property:h,value:b})}}function i(a){var b="";if(a)if("string"===
typeof a)a=a.toLowerCase(),(-1!==a.indexOf("min-width")||-1!==a.indexOf("max-width"))&&h(a);else for(var d=0,e=a.length;d<e;d++)1===a[d].type?(b=a[d].selectorText||a[d].cssText,-1!==b.indexOf("min-height")||-1!==b.indexOf("max-height")?h(b):(-1!==b.indexOf("min-width")||-1!==b.indexOf("max-width"))&&h(b)):4===a[d].type&&i(a[d].cssRules||a[d].rules)}var k=/,?([^,\n]*)\[[\s\t]*(min|max)-(width|height)[\s\t]*[~$\^]?=[\s\t]*"([^"]*)"[\s\t]*]([^\n\s\{]*)/mgi;this.init=function(){for(var a=0,b=document.styleSheets.length;a<
b;a++)i(document.styleSheets[a].cssText||document.styleSheets[a].cssRules||document.styleSheets[a].rules)}};window.addEventListener?window.addEventListener("load",b,!1):window.attachEvent("onload",b);this.L.ResizeSensor=function(a,b){function e(a,b){window.OverflowEvent?a.addEventListener("overflowchanged",function(a){b.call(this,a)}):(a.addEventListener("overflow",function(a){b.call(this,a)}),a.addEventListener("underflow",function(a){b.call(this,a)}))}function g(){this.q=[];this.add=function(a){this.q.push(a)};
var a,b;this.call=function(){a=0;for(b=this.q.length;a<b;a++)this.q[a].call()}}function h(a,b){function d(){var b=!1,e=a.resizeSensor.offsetWidth,f=a.resizeSensor.offsetHeight;i!=e&&(r.width=e-1+"px",n.width=e+1+"px",b=!0,i=e);k!=f&&(r.height=f-1+"px",n.height=f+1+"px",b=!0,k=f);return b}if(a.resizedAttached){if(a.resizedAttached){a.resizedAttached.add(b);return}}else a.resizedAttached=new g,a.resizedAttached.add(b);var h=function(){d()&&a.resizedAttached.call()};a.resizeSensor=document.createElement("div");
a.resizeSensor.className="resize-sensor";a.resizeSensor.style.cssText="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1;";a.resizeSensor.innerHTML='<div class="resize-sensor-overflow" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1;"><div></div></div><div class="resize-sensor-underflow" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1;"><div></div></div>';a.appendChild(a.resizeSensor);
if("absolute"!==(a.currentStyle?a.currentStyle.position:window.getComputedStyle?window.getComputedStyle(a,null).getPropertyValue("position"):a.style.position))a.style.position="relative";var i=-1,k=-1,r=a.resizeSensor.firstElementChild.firstChild.style,n=a.resizeSensor.lastElementChild.firstChild.style;d();e(a.resizeSensor,h);e(a.resizeSensor.firstElementChild,h);e(a.resizeSensor.lastElementChild,h)}if("array"===typeof a||"undefined"!==typeof jQuery&&a instanceof jQuery||"undefined"!==typeof Elements&&
a instanceof Elements)for(var i=0,k=a.length;i<k;i++)h(a[i],b);else h(a,b)}})();Erizo=Erizo||{};Erizo.View=function(){var b=Erizo.EventDispatcher({});b.url="http://chotis2.dit.upm.es:3000";return b};Erizo=Erizo||{};
Erizo.VideoPlayer=function(b){var a=Erizo.View({});a.id=b.id;a.stream=b.stream.stream;a.elementID=b.elementID;a.destroy=function(){a.video.pause();delete a.resizer;a.parentNode.removeChild(a.div)};a.resize=function(){var d=a.container.offsetWidth,e=a.container.offsetHeight;if(b.stream.screen||!1===b.options.crop)0.75*d<e?(a.video.style.width=d+"px",a.video.style.height=0.75*d+"px",a.video.style.top=-(0.75*d/2-e/2)+"px",a.video.style.left="0px"):(a.video.style.height=e+"px",a.video.style.width=4/3*
e+"px",a.video.style.left=-(4/3*e/2-d/2)+"px",a.video.style.top="0px");else if(d!==a.containerWidth||e!==a.containerHeight)0.75*d>e?(a.video.style.width=d+"px",a.video.style.height=0.75*d+"px",a.video.style.top=-(0.75*d/2-e/2)+"px",a.video.style.left="0px"):(a.video.style.height=e+"px",a.video.style.width=4/3*e+"px",a.video.style.left=-(4/3*e/2-d/2)+"px",a.video.style.top="0px");a.containerWidth=d;a.containerHeight=e};L.Logger.debug("Creating URL from stream "+a.stream);a.stream_url=(window.URL||
webkitURL).createObjectURL(a.stream);a.div=document.createElement("div");a.div.setAttribute("id","player_"+a.id);a.div.setAttribute("style","width: 100%; height: 100%; position: relative; background-color: black; overflow: hidden;");a.loader=document.createElement("img");a.loader.setAttribute("style","width: 16px; height: 16px; position: absolute; top: 50%; left: 50%; margin-top: -8px; margin-left: -8px");a.loader.setAttribute("id","back_"+a.id);a.loader.setAttribute("src",a.url+"/assets/loader.gif");
a.video=document.createElement("video");a.video.setAttribute("id","stream"+a.id);a.video.setAttribute("style","width: 100%; height: 100%; position: absolute");a.video.setAttribute("autoplay","autoplay");b.stream.local&&(a.video.volume=0);void 0!==a.elementID?(document.getElementById(a.elementID).appendChild(a.div),a.container=document.getElementById(a.elementID)):(document.body.appendChild(a.div),a.container=document.body);a.parentNode=a.div.parentNode;a.div.appendChild(a.loader);a.div.appendChild(a.video);
a.containerWidth=0;a.containerHeight=0;a.resizer=new L.ResizeSensor(a.container,a.resize);a.resize();a.bar=new Erizo.Bar({elementID:"player_"+a.id,id:a.id,stream:b.stream,media:a.video,options:b.options});a.div.onmouseover=function(){a.bar.display()};a.div.onmouseout=function(){a.bar.hide()};a.video.src=a.stream_url;return a};Erizo=Erizo||{};
Erizo.AudioPlayer=function(b){var a=Erizo.View({}),d,e;a.id=b.id;a.stream=b.stream.stream;a.elementID=b.elementID;L.Logger.debug("Creating URL from stream "+a.stream);a.stream_url=(window.URL||webkitURL).createObjectURL(a.stream);a.audio=document.createElement("audio");a.audio.setAttribute("id","stream"+a.id);a.audio.setAttribute("style","width: 100%; height: 100%; position: absolute");a.audio.setAttribute("autoplay","autoplay");b.stream.local&&(a.audio.volume=0);b.stream.local&&(a.audio.volume=0);
void 0!==a.elementID?(a.destroy=function(){a.audio.pause();a.parentNode.removeChild(a.div)},d=function(){a.bar.display()},e=function(){a.bar.hide()},a.div=document.createElement("div"),a.div.setAttribute("id","player_"+a.id),a.div.setAttribute("style","width: 100%; height: 100%; position: relative; overflow: hidden;"),document.getElementById(a.elementID).appendChild(a.div),a.container=document.getElementById(a.elementID),a.parentNode=a.div.parentNode,a.div.appendChild(a.audio),a.bar=new Erizo.Bar({elementID:"player_"+
a.id,id:a.id,stream:b.stream,media:a.audio,options:b.options}),a.div.onmouseover=d,a.div.onmouseout=e):(a.destroy=function(){a.audio.pause();a.parentNode.removeChild(a.audio)},document.body.appendChild(a.audio),a.parentNode=document.body);a.audio.src=a.stream_url;return a};Erizo=Erizo||{};
Erizo.Bar=function(b){var a=Erizo.View({}),d,e;a.elementID=b.elementID;a.id=b.id;a.div=document.createElement("div");a.div.setAttribute("id","bar_"+a.id);a.bar=document.createElement("div");a.bar.setAttribute("style","width: 100%; height: 15%; max-height: 30px; position: absolute; bottom: 0; right: 0; background-color: rgba(255,255,255,0.62)");a.bar.setAttribute("id","subbar_"+a.id);a.link=document.createElement("a");a.link.setAttribute("href","http://www.lynckia.com/");a.link.setAttribute("target","_blank");
a.logo=document.createElement("img");a.logo.setAttribute("style","width: 100%; height: 100%; max-width: 30px; position: absolute; top: 0; left: 2px;");a.logo.setAttribute("alt","Lynckia");a.logo.setAttribute("src",a.url+"/assets/star.svg");e=function(b){"block"!==b?b="none":clearTimeout(d);a.div.setAttribute("style","width: 100%; height: 100%; position: relative; bottom: 0; right: 0; display:"+b)};a.display=function(){e("block")};a.hide=function(){d=setTimeout(e,1E3)};document.getElementById(a.elementID).appendChild(a.div);
a.div.appendChild(a.bar);a.bar.appendChild(a.link);a.link.appendChild(a.logo);if(!b.stream.screen&&(void 0===b.options||void 0===b.options.speaker||!0===b.options.speaker))a.speaker=new Erizo.Speaker({elementID:"subbar_"+a.id,id:a.id,stream:b.stream,media:b.media});a.display();a.hide();return a};Erizo=Erizo||{};
Erizo.Speaker=function(b){var a=Erizo.View({}),d,e,g,h=50;a.elementID=b.elementID;a.media=b.media;a.id=b.id;a.stream=b.stream;a.div=document.createElement("div");a.div.setAttribute("style","width: 40%; height: 100%; max-width: 32px; position: absolute; right: 0;z-index:0;");a.icon=document.createElement("img");a.icon.setAttribute("id","volume_"+a.id);a.icon.setAttribute("src",a.url+"/assets/sound48.png");a.icon.setAttribute("style","width: 80%; height: 100%; position: absolute;");a.div.appendChild(a.icon);
a.stream.local?(e=function(){a.media.muted=!0;a.icon.setAttribute("src",a.url+"/assets/mute48.png");a.stream.stream.getAudioTracks()[0].enabled=!1},g=function(){a.media.muted=!1;a.icon.setAttribute("src",a.url+"/assets/sound48.png");a.stream.stream.getAudioTracks()[0].enabled=!0},a.icon.onclick=function(){a.media.muted?g():e()}):(a.picker=document.createElement("input"),a.picker.setAttribute("id","picker_"+a.id),a.picker.type="range",a.picker.min=0,a.picker.max=100,a.picker.step=10,a.picker.value=
h,a.picker.setAttribute("orient","vertical"),a.div.appendChild(a.picker),a.media.volume=a.picker.value/100,a.media.muted=!1,a.picker.oninput=function(){0<a.picker.value?(a.media.muted=!1,a.icon.setAttribute("src",a.url+"/assets/sound48.png")):(a.media.muted=!0,a.icon.setAttribute("src",a.url+"/assets/mute48.png"));a.media.volume=a.picker.value/100},d=function(b){a.picker.setAttribute("style","background: transparent; width: 32px; height: 100px; position: absolute; bottom: 90%; z-index: 1;"+a.div.offsetHeight+
"px; right: 0px; -webkit-appearance: slider-vertical; display: "+b)},e=function(){a.icon.setAttribute("src",a.url+"/assets/mute48.png");h=a.picker.value;a.picker.value=0;a.media.volume=0;a.media.muted=!0},g=function(){a.icon.setAttribute("src",a.url+"/assets/sound48.png");a.picker.value=h;a.media.volume=a.picker.value/100;a.media.muted=!1},a.icon.onclick=function(){a.media.muted?g():e()},a.div.onmouseover=function(){d("block")},a.div.onmouseout=function(){d("none")},d("none"));document.getElementById(a.elementID).appendChild(a.div);
return a};
